// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migmessagesenderrename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migmessagesenderrename));
        
        string IMigrationMetadata.Id
        {
            get { return "202108231308400_mig-messagesender-rename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
